name: 'Download Build Artifacts to different pathes'
description: 'Download build artifacts which where previously uploaded in the workflow by the upload-artifact action'
author: 'jason2866'
inputs: 
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false
outputs:
  download-path:
    description: 'Path of artifact download'
runs:
  using: 'node20'
  main: 'dist/index.js'
